### ISSUE TITLE
Cannot install because of requirements

### ISSUE THREAD

**Issue by ghost** [yiister/yii2-gentelella#1]
Hi, 

Thanks for this plugin but when I start "composer update" I get this error message : 
- The requested package yiister/yii2-gentelella \* is satisfiable by yiister/yii2-gentelella[dev-master] but these conflict with your requirements or minimum-stability.

I tried to change PHP version requirement to 5.5.0 but nothing.

I'm running basic app without any changes for information.

thanks for your help

**Comment by fps01** [comment]
Hello.
The extension has no stable version now. You have a `minimum-stability = stable` in your project.

Possible solutions:
1. You can set `minimum-stability = dev` (If it isn't production).
2. Waiting for a stable version. I think it's about one week.

**Comment by ghost** [comment]
Thanks for your answer, it works like a charm :)

Can't wait to have production version :p

**Comment by fps01** [comment]
@DarkRide It released!

**Comment by ghost** [comment]
Great ! Thanks
