### ISSUE TITLE
Composer error [InvalidArgumentException]

### ISSUE THREAD

**Issue by DenisAlliswell** [yiister/yii2-gentelella#11]
After [this](https://github.com/yiister/yii2-gentelella/issues/9) fix the following issue appeared:

``` bash
Installation failed, reverting ./composer.json to its original content.

[InvalidArgumentException]
Package bower-asset/gentelella--9999999.9999999.9999999.9999999 must have a source or dist specified

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
```

**Comment by jonatasfl** [comment]
Same error here.

**Comment by fps01** [comment]
It's a pity.
I'm on vacation now and I've no access to pc. I suggest the next solution:
1. Use `fxp/composer-asset-plugin:1.1.x`
2. Set minimal stability to `dev`
Both are no good idea.
But you can fix it and make a pull request. I merge it as soon as possible. It's the best way now.

**Comment by fps01** [comment]
@DenisAlliswell and @jonatasfl update `fxp/composer-asset-plugin` from `1.2.0` to `1.2.1` version, try to install `yiister/yii2-gentelella` and say me about result please.

**Comment by DenisAlliswell** [comment]
Works fine. Thanks!

**Comment by fps01** [comment]
You're welcome!
Thanks for a bug report!
