### ISSUE TITLE
Invalid path alias: @yiister/gentelella/assets/src

### ISSUE THREAD

**Issue by gangbo** [yiister/yii2-gentelella#14]
In yii2-app-advanced.
"yiister/yii2-gentelella": "^1.2"

**Comment by fps01** [comment]
@gangbo It's a very strange. What configuration do you use? I mean your environment.

**Comment by gangbo** [comment]
backend/config/main.php

```
'components' => [
        'view' => [
            'theme' => [
                'pathMap' => [
                    '@backend/views' => '@backend/themes/gentelella/views',
                ],
            ],
...
```

backend/themes/gentelella/views/layouts/main.php

```
$bundle = yiister\gentelella\assets\Asset::register($this);
```

**Comment by fps01** [comment]
@gangbo I installed a yii2-app-advanced and added the gentelella theme. It works.
