### ISSUE TITLE
Proper way to include animate.css in login page

### ISSUE THREAD

**Issue by prabowomurti** [yiister/yii2-gentelella#19]
What is the best practice to include css file `animate` and all javascripts in login page?

On my custom AppAsset/ Asset extends from `yiister\gentelella\assets\Asset`
```
...
public function loadLoginAsset()
{
    $this->css[] = 'css/animate.min.css';
}
....
```

Thank you

**Comment by fps01** [comment]
Hello @prabowomurti.
You can use solution above or add `$this->registerCssFile('path/to/file')` at the `login.php` view file.

P. S. Your variant preferer to implement in the package but this way requires an implementation of login page view.

**Comment by fps01** [comment]
Is the issue resolved?
