### ISSUE TITLE
Activate specific sub-menu in Menu widget

### ISSUE THREAD

**Issue by prabowomurti** [yiister/yii2-gentelella#20]
Is it possible to let the sub-menu open / active although we are not currently on the page. For example, I have a menu named "User" and it has 2 sub menus : "All User" and "Add User".

- User
-- All User
-- Add User
- Other Menu
- Another Menu

For example I have another submenu : "User Update" (user/update) and "User View" (user/view). When I open those pages, I need the "User" menu and all submenus to be open / showed.

A simple hack to solve the style 
```
<style type="text/css">
        /* temporary sidebar hack */
        li.active ul.nav.child_menu {
            display: block;
        }
        li>ul.nav.child_menu {
            display: none;
        }
    </style>
```
then we set the `active` to true on the sub menu
```
[
        "label" => "User",
        "icon" => "user-o",
        "url" => "#",
        "items" => [
            ["label" => "All User", "url" => ["user/index"], 
                'active' => $this->context->route == 'user/view' || $this->context->route == 'user/update'
                ],
            ["label" => "Add User", "url" => ["user/create"]],
        ],
    ],
```

What is your suggestion? Thank you.

**Comment by fps01** [comment]
I know the only one way to implement it: Extend `Menu` widget and overwrite `isItemActive` method with custom logic.

**Comment by fps01** [comment]
Is the issue resolved?

**Comment by prabowomurti** [comment]
The modified `Menu` widget : 
```
if (isset($item['active']) && $item['active']) 
            return true;

        parent::isItemActive($item);
```
doesn't help, because the `custom.js` file also handles the `current-page` class and `.slideDown()` function. The main menu is active, but the child menu is not opened.

```
// check active menu
	$SIDEBAR_MENU.find('a[href="' + CURRENT_URL + '"]').parent('li').addClass('current-page');

	$SIDEBAR_MENU.find('a').filter(function () {
		return this.href == CURRENT_URL;
	}).parent('li').addClass('current-page').parents('ul').slideDown(function() {
		setContentHeight();
	}).parent().addClass('active');
```

Does removing the above script solve the issue?

**Comment by fps01** [comment]
@prabowomurti Your solution looks like not bad. I'll check it. But also you can make a pull request. It would be nice.
