### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by fnaysee** [yiister/yii2-gentelella#21]
Hi, is this extension supports rtl layout ?

**Comment by fps01** [comment]
Hello @wp-src .
I didn't check it but a main repositoty had a similar issue https://github.com/puikinsh/gentelella/issues/161
Also the main repo has a fork with RTL support https://github.com/iPazooki/gentelella-RTL

**Comment by fnaysee** [comment]
Hi @fps01 .
If i use this extension i can replace the assets with that fork ? or doing so makes troubles ?

**Comment by fps01** [comment]
I think you can override main asset bundle via DI or change path to directory with bower package via yii aliases.
