### ISSUE TITLE
Create collapsible widget

### ISSUE THREAD

**Issue by SamMousa** [yiister/yii2-gentelella#22]
Yii-bootstrap already has a collapsible widget, it should be relatively simple to create one that's styled like gentelella's version.

**Comment by fps01** [comment]
Hello @SamMousa.
An extension has panel widget with a collapse effect (see http://gentelella.yiister.ru/site/panel). Is it can resolve your issue? If not Could you explain what to you mean?

**Comment by SamMousa** [comment]
https://colorlib.com/polygon/gentelella/general_elements.html#accordion1

I use your panels, they are good. But this is about the accordion!

**Comment by fps01** [comment]
I understood you.
It should be not so difficult to implement. I'll make it in future. Also you can make a PR with implementation.
