### ISSUE TITLE
Demo code in @bower/gentelella/build/js/custom.js

### ISSUE THREAD

**Issue by Alsodan** [yiister/yii2-gentelella#26]
custom.js is placed in theme asset. It has been taken from **@bower/gentelella/build/js** directory, becouse there is in vendor\yiister\yii2-gentelella\assets\ThemeAsset.php stand:

`public $sourcePath = '@bower/gentelella/build/';`

custom.js has demo code for Charts, Autocomplete, etc. It has 116Kb!

Maybe need use custom.js from **@bower/gentelella/src/js/** ? It has no demo data and its size is 7Kb.

**Comment by fps01** [comment]
@Alsodan hello. Sorry for late. I will try your solution.

**Comment by Alsodan** [comment]
In my application i use:

```
class CorrectThemeAsset extends AssetBundle
{
    public $sourcePath = '@bower/gentelella/';
    public $css = [
        'build/css/custom.min.css',
    ];
    public $js = [
        'src/js/custom.js',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapPluginAsset',
        'rmrevin\yii\fontawesome\AssetBundle',
        'yiister\gentelella\assets\BootstrapProgressbar',
    ];
}
```

**Comment by fps01** [comment]
@Alsodan I tried your code above. It threw `Uncaught TypeError: $(...).smartresize is not a function` js error in browser console.
