### ISSUE TITLE
Overlaping modals closing all modals

### ISSUE THREAD

**Issue by pascini** [yiister/yii2-gentelella#29]
When calling a modal from inside another modal, on clicking on submit, all modals are closed and the back screen (fade) remains. The only way to regain control off screen is refreshing the page.

**Comment by fps01** [comment]
Hello @pascini.
I advise you to close a modal before you're opening a new. Many modals at one moment are bad usability example.
P.S. This issue doesn't relate with Gentelella. Theme uses twitter boootstrap modals.
